// ── Offline backdrop plates ────────────────────────────────────────────────
// The backdrop card (layer 0 of every slab stack) is a HOLE FILLER, and the
// fill it does at runtime is described in DioramaScene.jsx's "backdrop's
// dis-occlusion fill" block as "the real-time half of the inpaint an offline
// pass would do properly". This is the offline half.
//
// source-assets/staircases/backdrop_inpaint.py removes everything past FILL.lo
// from the picture and paints the surround in over it, so layer 0 can be a
// plate that genuinely does not contain the lamp it is filling the hole
// behind. Two things the runtime dilation cannot do, which is the whole reason
// to bother: its outer tap ring reaches 10.5% of plate height and finds no
// background behind anything wider, and it only engages between FILL.lo and
// FILL.hi — so the NEAREST features, the ones with the most parallax travel
// and the worst ghosts, were never painted out at all.
//
// Keyed by the color plate's URL. A plate without an entry keeps the runtime
// dilation exactly as before, so this is opt-in per artwork.
//
// Written at QUARTER SIZE on purpose: the backdrop is never sampled above
// ~mip 3.5 (see blurBias) and is then sunk 0.35 toward the fog, so a
// full-resolution copy would be 19.7 MB of VRAM per plate to feed a surface
// that throws away all of it. Measured against a full-res plate at matching
// mip level: mean difference 0.9/255.
//
// (This lives in its own module rather than beside FILL because exporting a
// helper from DioramaScene.jsx breaks React fast-refresh — oxlint's
// react(only-export-components).)
export const BACKDROP_PLATES = {
  // Every plate the tour can hang. Generated by backdrop_inpaint.py, which
  // DISCOVERS plates rather than listing them — regenerate this block from
  // its discover() if a new MJ batch lands.
  //
  // Coverage varies a lot by plate (2.5%% to 33%% of the picture repainted).
  // The low ones are plates whose depth map puts almost nothing past the
  // FILL ramp, so their backdrop is nearly the painting — which is exactly
  // the old behaviour, and harmless. Any single plate can be dropped back to
  // the runtime dilation by deleting its entry here.
  '/nodes/descent/05-impossible-prison-staircases-var11.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var11-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var11-backdrop-depth.webp',
  },
  '/nodes/descent/05-impossible-prison-staircases-var16.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var16-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var16-backdrop-depth.webp',
  },
  '/nodes/descent/05-impossible-prison-staircases-var17.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var17-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var17-backdrop-depth.webp',
  },
  '/nodes/descent/05-impossible-prison-staircases-var19.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var19-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var19-backdrop-depth.webp',
  },
  '/nodes/descent/05-impossible-prison-staircases-var4.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var4-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var4-backdrop-depth.webp',
  },
  '/nodes/descent/05-impossible-prison-staircases-var9.webp': {
    color: '/nodes/descent/05-impossible-prison-staircases-var9-backdrop.webp',
    depth: '/nodes/descent/05-impossible-prison-staircases-var9-backdrop-depth.webp',
  },
  '/nodes/descent/impossible_1.webp': {
    color: '/nodes/descent/impossible_1-backdrop.webp',
    depth: '/nodes/descent/impossible_1-backdrop-depth.webp',
  },
  '/nodes/descent/impossible_2.webp': {
    color: '/nodes/descent/impossible_2-backdrop.webp',
    depth: '/nodes/descent/impossible_2-backdrop-depth.webp',
  },
  '/nodes/descent/impossible_3.webp': {
    color: '/nodes/descent/impossible_3-backdrop.webp',
    depth: '/nodes/descent/impossible_3-backdrop-depth.webp',
  },
  '/nodes/descent/impossible_4.webp': {
    color: '/nodes/descent/impossible_4-backdrop.webp',
    depth: '/nodes/descent/impossible_4-backdrop-depth.webp',
  },
  '/nodes/garden/01-moonlit-labyrinth-var0.webp': {
    color: '/nodes/garden/01-moonlit-labyrinth-var0-backdrop.webp',
    depth: '/nodes/garden/01-moonlit-labyrinth-var0-backdrop-depth.webp',
  },
  '/nodes/garden/01-moonlit-labyrinth-var1.webp': {
    color: '/nodes/garden/01-moonlit-labyrinth-var1-backdrop.webp',
    depth: '/nodes/garden/01-moonlit-labyrinth-var1-backdrop-depth.webp',
  },
  '/nodes/garden/01-moonlit-labyrinth-var2.webp': {
    color: '/nodes/garden/01-moonlit-labyrinth-var2-backdrop.webp',
    depth: '/nodes/garden/01-moonlit-labyrinth-var2-backdrop-depth.webp',
  },
  '/nodes/garden/01-moonlit-labyrinth-var3.webp': {
    color: '/nodes/garden/01-moonlit-labyrinth-var3-backdrop.webp',
    depth: '/nodes/garden/01-moonlit-labyrinth-var3-backdrop-depth.webp',
  },
  '/nodes/garden/02-endless-garden-starry-var0.webp': {
    color: '/nodes/garden/02-endless-garden-starry-var0-backdrop.webp',
    depth: '/nodes/garden/02-endless-garden-starry-var0-backdrop-depth.webp',
  },
  '/nodes/garden/02-endless-garden-starry-var1.webp': {
    color: '/nodes/garden/02-endless-garden-starry-var1-backdrop.webp',
    depth: '/nodes/garden/02-endless-garden-starry-var1-backdrop-depth.webp',
  },
  '/nodes/garden/02-endless-garden-starry-var2.webp': {
    color: '/nodes/garden/02-endless-garden-starry-var2-backdrop.webp',
    depth: '/nodes/garden/02-endless-garden-starry-var2-backdrop-depth.webp',
  },
  '/nodes/garden/02-endless-garden-starry-var3.webp': {
    color: '/nodes/garden/02-endless-garden-starry-var3-backdrop.webp',
    depth: '/nodes/garden/02-endless-garden-starry-var3-backdrop-depth.webp',
  },
  '/nodes/garden/03-solitary-pavilion-var0.webp': {
    color: '/nodes/garden/03-solitary-pavilion-var0-backdrop.webp',
    depth: '/nodes/garden/03-solitary-pavilion-var0-backdrop-depth.webp',
  },
  '/nodes/garden/03-solitary-pavilion-var1.webp': {
    color: '/nodes/garden/03-solitary-pavilion-var1-backdrop.webp',
    depth: '/nodes/garden/03-solitary-pavilion-var1-backdrop-depth.webp',
  },
  '/nodes/garden/03-solitary-pavilion-var2.webp': {
    color: '/nodes/garden/03-solitary-pavilion-var2-backdrop.webp',
    depth: '/nodes/garden/03-solitary-pavilion-var2-backdrop-depth.webp',
  },
  '/nodes/garden/03-solitary-pavilion-var3.webp': {
    color: '/nodes/garden/03-solitary-pavilion-var3-backdrop.webp',
    depth: '/nodes/garden/03-solitary-pavilion-var3-backdrop-depth.webp',
  },
  '/nodes/garden/04-gothic-library-var0.webp': {
    color: '/nodes/garden/04-gothic-library-var0-backdrop.webp',
    depth: '/nodes/garden/04-gothic-library-var0-backdrop-depth.webp',
  },
  '/nodes/garden/04-gothic-library-var1.webp': {
    color: '/nodes/garden/04-gothic-library-var1-backdrop.webp',
    depth: '/nodes/garden/04-gothic-library-var1-backdrop-depth.webp',
  },
  '/nodes/garden/04-gothic-library-var2.webp': {
    color: '/nodes/garden/04-gothic-library-var2-backdrop.webp',
    depth: '/nodes/garden/04-gothic-library-var2-backdrop-depth.webp',
  },
  '/nodes/garden/04-gothic-library-var3.webp': {
    color: '/nodes/garden/04-gothic-library-var3-backdrop.webp',
    depth: '/nodes/garden/04-gothic-library-var3-backdrop-depth.webp',
  },
};

// Every file a gallery needs before it can be hung, backdrop included.
//
// Tour's restock warms the loader cache "under the same key useTexture will ask
// for, so the re-render finds the plates already decoded and never suspends" —
// and Painting asks for FOUR urls where a plate has a backdrop. Preloading only
// the painting's two would leave the other two to suspend mid-tour, which is
// the one thing that path exists to prevent. So the list is derived here, and
// every caller reads it rather than restating it.
export const platesOf = (scene) => {
  const b = BACKDROP_PLATES[scene.color];
  return b ? [scene.color, scene.depth, b.color, b.depth]
           : [scene.color, scene.depth];
};
